name: rental_santuy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.13
  modal_bottom_sheet: ^2.0.1
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.7
  google_sign_in: ^5.3.2
  font_awesome_flutter: ^9.0.0
  provider: ^6.0.3
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/kendaraan/
    - lib/assets/avatars/
    - lib/assets/banner/


